version: 2.1

parameters:
  browser:
    type: string
    default: ${DEFAULT_BROWSER}
  desktop:
    type: string
    default: "false"


executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers

commands:
  env_setup:
    description: "Set up the test environment"
    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "package-lock.json" }}
      - run: npm install --progress=false
      - save_cache:
          key: v1-node-modules-{{ checksum "package-lock.json" }}
          paths: node_modules


  upload_results:
    description: "Upload any test artifacts"
    steps:
      - store_test_results:
          path: ./artifacts/test-results
      - when:
          condition: on_fail
          steps:
            - store_artifacts:
                path: ./artifacts

jobs:
  regression_build:
    executor: docker_node
    steps:
      - env_setup
      - run_regressions:
          command: | 
            echo '<< parameters.browser >>'
      - upload_results

workflows:
  staging_full_regression_run:
    jobs:
      - regression_build:
          name: regressionNamed1
      - regression_build:
          name: Promotions