
name: Merge PRs!

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - approved

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: MERGE
          MAXIMUM_RETRIES: 2
